### ISSUE TITLE
$s_timeline_no_activity 中文翻譯錯誤

### ISSUE THREAD

**Issue by flamerecca** [meedan/MantisBT#1]
MantisBT/lang/strings_chinese_traditional.txt 內 第 1243 行

$s_timeline_no_activity = '在時間範圍內沒有任合使用動作。';
應該為「在時間範圍內沒有任何使用動作。」

**Comment by infojunkie** [comment]
Thanks for your submission, but it would be better to submit this to the upstream repo https://github.com/mantisbt/mantisbt
